#!/usr/local/bin/zsh

# This assumes you are in zsh, i.e. ./install in zsh
# Should be agnostic

# Source zshrc
source $HOME/.zshrc

# Source tmux
tmux source-file ~/.tmux.conf

# Install tmux plugins
./tmux/plugins/tpm/scripts/install_plugins.sh

# Install fonts
./fonts/powerline/install.sh

# Install vim plugins
nvim -u $HOME/.dotfiles/vim/init.vim +PlugClean +PlugInstall +PlugUpdate +qall

# Install pyenv Python Versions
pyenv install 3.6.9
pyenv global 3.6.9


reload

# Install AWS CLI
pip3 install 3.6.9
