# Dotfiles home shorthand
export DF=$HOME/.dotfiles
export DFL=$HOME/.dotfiles_local

source $DFL/env

export AUTOLOAD_HOME=$DF/zsh/autoload

# TMUX Plugin config
export ZSH_TMUX_AUTOSTART=true
export ZSH_TMUX_AUTOQUIT=false

# Language and Encoding
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Avoid duplicates in your bash history
export HISTCONTROL="erasedups:ignoreboth"

# Virtualenv variables
export WORKON_HOME=~/.virtualenvs
export PROJECT_HOME=~/Projects

# ZPLUG Home
export ZPLUG_HOME=$DF/zsh/zplug

# Gitflow
export FLAGS_GETOPT_CMD="/usr/bin/getopt"

export PATH="$PATH:/Users/hashbang/.pyenv/bin"
if [ -z "$VIRTUAL_ENV" ]; then
    eval "$(pyenv init -)"
fi
