# Dotfiles home shorthand
export DF=$HOME/.dotfiles
export DFL=$HOME/.dotfiles_local

export FUNCTIONS_HOME=$DF/zsh/functions
export AUTOLOAD_HOME=$DF/zsh/autoload

# TMUX Plugin config
export ZSH_TMUX_AUTOSTART=true
export ZSH_TMUX_AUTOQUIT=false

# Language and Encoding
export LC_ALL=en_US.UTF-8
export LANG=en_US.UTF-8

# Avoid duplicates in your bash history
export HISTCONTROL="erasedups:ignoreboth"

# Virtualenv variables
export WORKON_HOME=~/.virtualenvs
export PROJECT_HOME=~/Projects

# Require virtualenv for pip, reduce garbage on global
export PIP_REQUIRE_VIRTUALENV=true

# ZPLUG Home
export ZPLUG_HOME=$DF/zplug

# Load all files from .shell/zshrc.d directory
if [ -d $FUNCTIONS_HOME ]; then
  for file in $FUNCTIONS_HOME/*; do
    source $file
  done
fi
