consrc () {
  [[ -f "$1" ]] && source "$1"
}

consrc $DFL/env

# Load ZPLUG
source $ZPLUG_HOME/init.zsh

zplug "plugins/virtualenv", from:oh-my-zsh
zplug "plugins/tmux", from:oh-my-zsh
zplug "plugins/git", from:oh-my-zsh
zplug "plugins/git-flow-avh", from:oh-my-zsh
zplug "lib/clipboard", from:oh-my-zsh, if:"[[ $OSTYPE == *darwin* ]]"
zplug "lib/history", from:oh-my-zsh

zplug "petervanderdoes/git-flow-completion", from:github
zplug "zsh-users/zsh-completions", from:github
zplug "zsh-users/zsh-syntax-highlighting", from:github

# Prompt theme
zplug "caiogondim/bullet-train.zsh", from:github, as:theme

# Local plugins
zplug "$DF/zsh/plugins/key-bindings", from:local
zplug "$DF/zsh/plugins/fzf-zsh", from:local
zplug "$DF/zsh/plugins/tmux-autoworkon", from:local

# Install plugins if there are plugins that have not been installed
if ! zplug check --verbose; then
    printf "Install? [y/N]: "
    if read -q; then
        echo; zplug install
    fi
fi

# Start loading plugins
zplug load

autoload -U compinit && compinit

# Load all files from .shell/zshrc.d directory
if [ -d $AUTOLOAD_HOME ]; then
  for file in $AUTOLOAD_HOME/*; do
    source $file
  done
fi

# Conditionally load venvwrapper
consrc "/usr/local/bin/virtualenvwrapper.sh"

consrc $DFL/zshrc
consrc $DFL/zsh_aliases


# tabtab source for serverless package
# uninstall by removing these lines or running `tabtab uninstall serverless`
[[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh ]] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/serverless.zsh
# tabtab source for sls package
# uninstall by removing these lines or running `tabtab uninstall sls`
[[ -f /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh ]] && . /usr/local/lib/node_modules/serverless/node_modules/tabtab/.completions/sls.zsh