# Path to your oh-my-zsh installation.
export ZSH=$HOME/.oh-my-zsh
export ZSH_CUSTOM=$HOME/.dotfiles/zsh/omz-custom
source ~/.dotfiles_local/env

# Theme
ZSH_THEME="bullet-train/bullet-train"

# Tab-completion interface
COMPLETION_WAITING_DOTS="true"

# TMUX Plugin config
ZSH_TMUX_AUTOSTART=true
ZSH_TMUX_AUTOQUIT=false

# ZSH VI Mode Config
export KEYTIMEOUT=1
MODE_INDICATOR="%{$fg_bold[red]%}%{$fg[red]%}[NORMAL]%{$reset_color%}"

# OMZ Plugins
plugins=(virtualenv tmux git zsh-syntax-highlighting)

# User configuration

# Encoding
export LC_ALL=en_US.UTF-8

# Language
export LANG=en_US.UTF-8

# Avoid duplicates in your bash history
export HISTCONTROL="erasedups:ignoreboth"

[ -f ~/.fzf.zsh ] && source ~/.fzf.zsh

# Virtualenv variables
export WORKON_HOME=~/.virtualenvs
export PROJECT_HOME=~/Projects
source /usr/local/bin/virtualenvwrapper.sh

# Require virtualenv for pip, reduce garbage on global
export PIP_REQUIRE_VIRTUALENV=true

# Exporting any saved tmux env so that zsh can access it
for var in $(tmux show-environment | grep "TMUX_VENV"); do
  eval "export $var";
done;

# If pyvenv is set for this window, new panes will activate it
VENV_VAR="TMUX_VENV$(tmux display-message -p '#I')"
VENV_PATH=(${(P)VENV_VAR})
if [[ -n "$VENV_PATH" ]]; then
  workon `basename $VENV_PATH`
fi

# Finally load OMZ, Aliases, then local settings
source $ZSH/oh-my-zsh.sh
source ~/.zsh_aliases
source ~/.dotfiles_local/zshrc
